dashboard_page:
    class: Dashboard
    method: index
    namespace : Beagle\CMS\Controller
    url: "/admin/dashboard" 
    
login_page:
    class: User 
    method: login
    namespace : Beagle\CMS\Controller
    url: "/admin/login" 

register_page:
    class: User 
    method: register
    namespace : Beagle\CMS\Controller
    url: "/admin/register"
    
update_page:
    class: User 
    method: update
    namespace : Beagle\CMS\Controller
    url: "/admin/user/update"    
    
home_page:
    class: Page
    method: index
    namespace : Beagle\CMS\Controller
    url: "/{page_id}"    